name: SimplePvP
version: 1.0
main: io.github.hoitemmiecoleg.simplepvp.main
api-version: 1.13

load: STARTUP

commands:
  pvpspawn1:
    aliases:
      - ps1
    permission: simplepvp.admin
  pvp:
    aliases:
      - pvpworld
    permission: simplepvp.pvp
    description: "This command takes you to the pvp world."
    usage: "You must be a player to use this command!"
permissions:
  simplepvp.admin:
    default: op
  simplepvp.pvp:
    default: true